config/routes.rb
Rails.application.routes.draw do
  
  resources :quotes
  resources :user_tasks

  delete '/user_tasks/destroy/:id', to: 'user_tasks#destroy1', as: 'destroy1'

  root 'home#index'


  get 'manage', to: 'user_tasks#manage', as: 'manage'

  get 'admin/quotes', to: 'quotes#admin', as: 'admin_quote'

  get 'user/quotes', to: 'quotes#user', as: 'user_quote'

  devise_for :users, :controllers => { registrations: 'registrations' }

  get '/email_subscribe', to: 'email_subscribes#email_subscribe_get', as: 'email_get'
  
  get '/about_me', to: 'home#about_me', as: 'about_me'
  
  get '/how_this_works', to: 'home#how_this_works', as: 'how_this_works'

  post '/email_subscribe_post', to: 'email_subscribes#email_subscribe_post', as: 'email_post'
  
end

app/models/quote.rb
class Quote < ApplicationRecord
	belongs_to :user, optional: true
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :authenticate_user!
  def index
    @quotes = Quote.all.where(status: "approved").order(:id)
    @random = Quote.order("RANDOM()").where(status: "approved").limit(6)
  end

  def new
    @quote = Quote.new
  end

  def user
    @random = Quote.order("RANDOM()").where(status: "approved").limit(6)
    if current_user.admin
      @pending = current_user.quotes.where(status: "pending").order(:id)
    else
      @pending = current_user.quotes.order(:id)
    end
    @count_approve = Quote.all.where(status: "approved").count.to_s
    @filter = "Click to view all " + @count_approve + " Quotes"
  end

  def create
    @quote = Quote.create(quote_params_good)
    if @quote.save
      if !current_user.admin
        TestMailer.alert_admin(current_user, @quote).deliver_now 
      end
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    if current_user.admin
      @quote = Quote.find(params[:id])
    else
      redirect_to quotes_path
    end
  end

  def admin
    if current_user.admin
      @quotes = Quote.all.order(:id)
      @pending = Quote.where(status: "pending").order(:id)
    else
      redirect_to quotes_path
    end
  end

  def update
    @quote = Quote.find(params[:id])
    if @quote.update(admin_edit)
      redirect_to root_path, danger: "Updated successfully Dude"
    else
      render 'edit'
    end
  end

  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy
    if current_user.admin
      redirect_to admin_quote_path
      else
      redirect_to quotes_path
    end
  end

  private 

  def quote_params_good
    params.require(:quote).permit(:quotes, :author, :user_id, :status)
  end
  def admin_edit
    params.require(:quote).permit(:quotes, :author, :status)
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/admin.html.erb
<div class="container">
	<div >
		<h1>Pending quotes submited by users ( <%= @pending.count %> ) </h1>
		<% @pending.each do |pending| %>
			<%= pending.quotes %><br>
			<%= link_to "Edit" , edit_quote_path(pending) %>
			<%=  link_to "Delete", quote_path(pending), method: :delete, class: "text-danger" %><hr>
		<% end %>
	</div>
	<div>
		<h1>All quotes</h1>
		<% @quotes.each do |quote| %>
		<%= quote.quotes %><br>
		<%= link_to "Edit" , edit_quote_path(quote) %>
		<%=  link_to "Delete", quote_path(quote), method: :delete, class: "text-danger" %><hr>
		<% end %>
	</div>
</div>
<style>
    .neat {
            min-height: calc(100vh - 143px);
           }
  </style>

app/views/quotes/edit.html.erb
<div class="container">

	<%= form_for @quote do |form| %>
    <% if @quote.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this Task from being saved:</h2>

        <ul>
          <% @quote.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    <div class="field">
      <%= form.label :quote %>
      <%= form.text_area :quotes, class: 'form-control' %>
    </div>


    <div class="field">
      <%= form.label :author %>
      <%= form.text_field :author, class: 'form-control', placeholder: "Author name only please" %>
    </div>

    <% if current_user.admin %>
	    <div class="field mt-3">
	    	<%= form.select :status, ['pending','approved', 'reject'], class: "form-control"%>
	    </div>
    <% end %>

    <div class="actions">
      <%= form.submit "Update", class: "btn btn-success btn-block mt-3" %>
    </div>

    <% end %>
</div>

app/views/quotes/index.html.erb
<div class="container">
	<h2 class="ml-3">Total <%= @quotes.count %> QUOTES</h2>
	<center>
		<%= link_to '<i class="fas fa-plus"></i> <b>Submit Your Quote</b>'.html_safe, new_quote_path, class: "btn btn-info mb-3" %>
	</center>
	<% color = ["primary", "danger", "success", "warning"] %>
	<% num = 0 %>
	<% @quotes.each do |quotes| %>
		<% shuff = color.shuffle.first %>
		<% if shuff == "primary" %>
			<% shawcol = "rgb(0,123,255)" %>			
		<% elsif shuff ==  "danger" %>
			<% shawcol = "rgb(220,53,69)" %>
		<% elsif shuff == "success" %>
			<% shawcol = "rgb(40,167,69)" %>
		<% elsif shuff == "warning" %>
			<% shawcol = "rgb(255,193,7)" %>
		<% end %>
		<% num +=1 %>
		<div class="card mb-3 border-<%= shuff %> rounded1 havar" style="box-shadow:   13px 34px 70px -20px <%= shawcol %>">
		  <div class="card-body">
		    <blockquote class="blockquote mb-0 text-right">
		      <p><%= num %> . <b><%= quotes.quotes %></b></p>
		      <footer class="blockquote-footer"><cite title="Source Title"><%= quotes.author %></cite></footer>
		    </blockquote>
		  </div>
		  <div class="card-footer border-secondary">
		  	<span>
		    Posted by : <% if !quotes.user.admin %>
		    	<%= quotes.user.email.capitalize %>
		    <% elsif %>
		    	Admin
		    <% end %></span>
		  </div>
		</div>
	<% end %>
</div>
<style>
    .neat {
            min-height: calc(100vh - 143px);
           }
           .havar {
           	transition:  0.4s;
           }
   	.havar:hover {
   		-webkit-transform: scale(1.1);
        -ms-transform: scale(1.1);
        transform: scale(1.1);
        
   			}
  </style>

app/views/quotes/new.html.erb
<div class="container">

	<%= form_for @quote do |form| %>


    <div class="field">
      <%= form.label :quote %>
      <%= form.text_area :quotes, class: 'form-control',required: "true" %>
    </div>

    <%= form.hidden_field :user_id, value: current_user.id %>

    <div class="field">
      <%= form.label :author %>
      <%= form.text_field :author, class: 'form-control', placeholder: "Please enter only Author Name",required: "true" %>
    </div>

    <div class="actions">
      <%= form.submit "Submit", class: "btn btn-success btn-block mt-3" %>
    </div>

    <% end %>
</div>
<style>
    .neat {
            min-height: calc(100vh - 143px);
           }
  </style>

app/views/quotes/user.html.erb
<div class="container">
	<center>
		<%= link_to '<i class="fas fa-plus"></i> <b>Submit Your Quote</b>'.html_safe, new_quote_path, class: "btn btn-info mb-3 mt-2" %>
	</center>
	<div class="row">
	<div class="col-lg-6 mb-4">
		<div class="card" >
  		<div class="card-header"><h4 class="text-center">Quotes, which you Submitted</h4><% if current_user.admin %> Admin only can see pending Quotes that created by you, don't confuse , this page is for users not admins <% end %></div>
		<table class="table">
		  <thead class="thead-light">
		    <tr>
		      <th scope="col">Quote <small class="text-muted">( Click to view )</small></th>
		      <th scope="col">Status</th>
		      <th scope="col">Actions</th>
		    </tr>
		  </thead>
		  <tbody>
			<% @pending.each do |pending| %>
		  		<tr>
			      <td><a class="text-primary" data-toggle="modal" data-target="#ModalView<%= pending.id %>"><%= pending.quotes.capitalize.truncate(18) %></a></td>
			      <td>
			      	<% if pending.status == "pending" %>
			      		<span class="badge badge-warning p-2">Pending</span>
			      	<% elsif pending.status == "approved" %>
			      		<span class="badge badge-success p-2">Approved</span>
			      	<% else %>
			      		<span class="badge badge-danger p-2">Rejected</span>
			      	<% end %>
			      </td>
			      	<td>
			      		<% if pending.status == "pending" %>
				      	<a class="text-primary" data-toggle="modal" data-target="#ModalEdit<%= pending.id %>">Edit </a> <a class="text-danger" data-toggle="modal" data-target="#ModalDelete<%= pending.id %>">
						  Delete
						</a> 
			      	<% else %>
			      		<i class="fal fa-minus-circle"></i> None
			      	<% end %>	

					<!-- Modal for View -->
					<div class="modal fade" id="ModalView<%= pending.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
					  <div class="modal-dialog modal-dialog-centered" role="document">
					    <div class="modal-content">
					      <div class="modal-header bg-info">
					        <h5 class="modal-title text-white" id="exampleModalLongTitle">View Your QUOTE</h5>
					        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
					          <span aria-hidden="true">&times;</span>
					        </button>
					      </div>
					      <div class="modal-body">
					        <b>Author: </b> <%= pending.author.capitalize %><br>
					        <b>Quote : </b> <%= pending.quotes.capitalize %>
					      </div>
					      <div class="modal-footer">
					        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					      </div>
					    </div>
					  </div>
					</div>

			      		<!-- Modal for Edit -->
						<div class="modal fade" id="ModalEdit<%= pending.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
						  <div class="modal-dialog modal-dialog-centered" role="document">
						    <div class="modal-content">
						      <div class="modal-header bg-primary">
						        <h5 class="modal-title text-white" id="exampleModalCenterTitle"><i class="fas fa-pen-square"></i> Edit your Quote</h5>
						        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
						          <span aria-hidden="true">&times;</span>
						        </button>
						      </div>
						      <div class="modal-body">
						        <%= form_for pending do |form| %>

							    <div class="field">
							      <b>Quote</b>
							      <%= form.text_area :quotes, class: 'form-control' %>
							    </div>

							    <%= form.hidden_field :user_id, value: current_user.id %>

							    <div class="field">
							      <b>Author</b>
							      <%= form.text_field :author, class: 'form-control', placeholder: "Author name only please" %>
							    </div>

							    <% if current_user.admin %>
								    <div class="field mt-3">
								    	<%= form.select :status, ['pending','approved', 'reject'], class: "form-control"%>
								    </div>
							    <% end %>

						      </div>
						      <div class="modal-footer">
						        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
						        <%= form.submit "Update", class: "btn btn-success" %>
						        <% end %>
						      </div>
						    </div>
						  </div>
						</div>


						<!-- Modal -->
									<div class="modal fade" id="ModalDelete<%= pending.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
									  <div class="modal-dialog modal-dialog-centered" role="document">
									    <div class="modal-content">
									      <div class="modal-header bg-danger">
									        <h5 class="modal-title text-white" id="exampleModalLongTitle"><i class="fas fa-trash"></i> Delete</h5>
									        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
									          <span aria-hidden="true">&times;</span>
									        </button>
									      </div>
									      <div class="modal-body">
									        Are you sure to delete <span class="text-danger"><strong><%= pending.quotes %></strong></span> ?
									      </div>
									      <div class="modal-footer">
									        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
									        <%= link_to "Delete" , pending, method: :delete, class: "btn btn-danger" %>
									      </div>
									    </div>
									  </div>
									</div>
						<% end %>
				  </td>
			    </tr>
		  </tbody>
		</table>
	</div>
</div>

	<div class="col-lg-6">
		<div class="card">
		  <div class="card-header">
		    <h4>These are random 5 Quotes</h4> 
		    <%= link_to @filter , quotes_path , class: "btn btn-sm btn-danger" %>
		  </div>
		  <div class="card-body">
		  	<% @random.each do |random| %>
		  	<blockquote class="blockquote mb-0">
		      <p><%= random.quotes.capitalize %></p>
		      <footer class="blockquote-footer"><cite title="Source Title"><%= random.author.capitalize %></cite></footer>
		    </blockquote><hr>
		  	<% end %>
		  </div>
		</div>
	</div>
</div> <!-- row end -->

</div>
<style>
    .neat {
            min-height: calc(100vh - 143px);
           }
  </style>