config/routes.rb
Rails.application.routes.draw do
  
  resources :quotes
  resources :user_tasks

  delete '/user_tasks/destroy/:id', to: 'user_tasks#destroy1', as: 'destroy1'

  root 'home#index'


  get 'manage', to: 'user_tasks#manage', as: 'manage'

  get 'admin/quotes', to: 'quotes#admin', as: 'admin_quote'

  get 'user/quotes', to: 'quotes#user', as: 'user_quote'

  devise_for :users, :controllers => { registrations: 'registrations' }

  get '/email_subscribe', to: 'email_subscribes#email_subscribe_get', as: 'email_get'
  
  get '/about_me', to: 'home#about_me', as: 'about_me'
  
  get '/how_this_works', to: 'home#how_this_works', as: 'how_this_works'

  post '/email_subscribe_post', to: 'email_subscribes#email_subscribe_post', as: 'email_post'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" href="https://img.icons8.com/fluent/48/000000/todo-list.png">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.2.0/dist/confetti.browser.min.js"></script>
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css">
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.11"></script>
     <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
      <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
      <link href="https://fonts.googleapis.com/css2?family=Kalam&display=swap" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-light color2">
  <img src="https://img.icons8.com/fluent/48/000000/todo-list.png" class="mr-1" style="width: 30px" /> <%= link_to "Todo YO!!", "#", class: "navbar-brand text-dark" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link text-dark" %> 
      </li>
      <% if current_user %>
      <li class="nav-item active">
        <%= link_to "Manage", manage_path , class: "nav-link text-dark" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Quotes", user_quote_path, class: "nav-link text-dark" %>
      </li>
      <% end %>
      <li class="nav-item active">
        <%= link_to "About us", about_me_path , class: "nav-link text-dark" %>
      </li>
      <li class="nav-item active">
        <%= link_to "How this work", how_this_works_path, class: "nav-link text-dark" %>
      </li>
      
    </ul>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if !current_user %>
      <li>
        <span class="mr-2 mb-1"><%= link_to '<i class="fas fa-sign-in-alt"></i> Log-in'.html_safe, new_user_session_path, class: "btn btn-outline-success text-dark" %></span> || <span class="mx-2 "><%= link_to '<i class="fas fa-user-plus"></i> sign-up'.html_safe, new_user_registration_path, class: "btn btn-outline-warning text-dark" %></span>
      </li>
      <li>
        
      </li>
      <% end %>
      <li class="nav-item dropdown">
        <% if current_user %>
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.email.camelcase %>
        </a>
        <% end %>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
           <% if current_user %>
           <%= link_to "Edit details", edit_user_registration_path(current_user), class: "dropdown-item" %>
            <%= link_to "logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <% end %>
      </li>
    </ul>
  </div>
</nav>

   <% if current_user && current_user.admin? %>
    <div>
      <button type="button" class="btn btn-danger btn-sm btn-disabled admin">You are Iron Man</button>
    </div>
    <% end %>
    <div class="neat"><%= yield %></div>
    <!-- Footer -->
    <footer class="footer sticky font-small color3 pt-4 mt-4">

      <!-- Footer Elements -->
      
      <!-- <div class="container"> -->

        <!-- Call to action -->
        <!-- <ul class="list-unstyled list-inline text-center pt-1">
          <li class="list-inline-item">
            <h5 class="mb-1 text-white">Register for free</h5>
          </li>
          <li class="list-inline-item">
            
          </li>
          <li class="list-inline-item">
           <span class="text-warning"> © 2020 Copyright: <span class="text-white">TODO</span></span>
          </li>
        </ul> -->
        <!-- Call to action -->

      <!-- </div> -->
      
      <!-- Footer Elements -->

      <!-- Copyright -->
      <div class="footer-copyright text-center pb-3 text-warning">
        <% if !current_user %>
      <span class=" text-white" style="font-size: 20px">Register for free</span> <%= link_to "Sign up!", new_user_registration_path, class: "btn btn-outline-secondary btn-rounded text-white" %> <span class="text-white">||<% end %></span> © 2020 Copyright:
        <%= link_to "TODO", root_path, class: "text-white" %>
      </div>
      <!-- Copyright -->
    </footer>
  </body>
</html>

<script >
      window.setTimeout(function() {
        $(".alert").fadeTo(500, 0).slideUp(500, function(){
            $(this).remove(); 
        });
    }, 5000);
</script>
<style>
  .admin {
        position: fixed;
        z-index: 999;
        right: 0;
        top: 115px;
      }
      .color2 {
        background-color: #EAF0F1;
    border-color: #EAF0F1
  
  }
  .color3 {
        background-color: #2B2B52;
    border-color: #2B2B52
  
  }

  
</style>

app/views/layouts/bootstrap-mailer.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <%= stylesheet_link_tag "application-mailer", media: "all" %>
  </head>
  <body >
  	<div class="container" >
	  	<div >
	  		<div style="height: 200px;background-image: url('https://i.ibb.co/FnrXp6C/rsz-1new1.jpg');background-position: center;background-repeat: no-repeat;background-size: cover;position: relative;border-top-left-radius: 10px;
	border-top-right-radius: 10px;" class="kapa"><center><span class="pt-5 " style="font-size: 22px">Todo Application</span></center>	
	  		</div>
	  		<div class="hellboy borderdiv" >
		  		<div class="pad mb-2 ">
			    	<%= yield %>
			    </div>
			</div>
		</div>
    </div>
  </body>
</html>
<style >
	.qi, .ri {
    color: black; 
}
.im {
    color: black;
}
.borderdiv {
	border-bottom: 5px solid black;
	/*border-left: 1px solid black;
	border-right: 1px solid black;*/
	border-bottom-left-radius: 10px;
	border-bottom-right-radius: 10px;
}
.pad {
	padding:8px;
}
/*.kapa {
	border-left: 4px solid black;
}*/
</style>