config/routes.rb
Rails.application.routes.draw do
  
  resources :quotes
  resources :user_tasks

  delete '/user_tasks/destroy/:id', to: 'user_tasks#destroy1', as: 'destroy1'

  root 'home#index'


  get 'manage', to: 'user_tasks#manage', as: 'manage'

  get 'admin/quotes', to: 'quotes#admin', as: 'admin_quote'

  get 'user/quotes', to: 'quotes#user', as: 'user_quote'

  devise_for :users, :controllers => { registrations: 'registrations' }

  get '/email_subscribe', to: 'email_subscribes#email_subscribe_get', as: 'email_get'
  
  get '/about_me', to: 'home#about_me', as: 'about_me'
  
  get '/how_this_works', to: 'home#how_this_works', as: 'how_this_works'

  post '/email_subscribe_post', to: 'email_subscribes#email_subscribe_post', as: 'email_post'
  
end

app/models/user_task.rb
class UserTask < ApplicationRecord
	has_many :todos, dependent: :destroy
	belongs_to :user
	accepts_nested_attributes_for :todos, reject_if: :all_blank, allow_destroy: true
	validates_presence_of :user_id
end

app/controllers/user_tasks_controller.rb
 class UserTasksController < ApplicationController
  before_action :authenticate_user!
  def index
  	@tasks = current_user.user_tasks.order(:id )
    @quote = Quote.order("RANDOM()").first
  end

  def new
  	@task = UserTask.new
    @task.todos.build
    @quote = Quote.order("RANDOM()").first
  end

  def create

  	@task = UserTask.create(user_task_params)
  	if @task.save
      if current_user.subscribe?
        TestMailer.test_mail_user(current_user, @task).deliver_now
      end
      redirect_to user_tasks_path,success: "#{@task.name.capitalize} is successfully created"
  	else
  		render 'new'
  	end

  end

  def edit
  	@task = current_user.user_tasks.find(params[:id])
  end

  def update

  	@task = UserTask.find(params[:id])
  	if @task.update(user_task_params)
      if @task.todos.where(completed: true).count == @task.todos.count
        @task.completed = true
        @task.save
        redirect_to user_task_path(@task),success: "Hurray All Tasks Completed"
      else
        @task.completed = false
        @task.save
        redirect_to user_task_path(@task)
      end
  		
  	else
  		render 'edit'
  	end

  end

  def destroy
      @task = current_user.user_tasks.find(params[:id])
      @task.destroy
      redirect_to manage_path, danger: "#{@task.name.capitalize} Todo Deleted" 
  end

  def destroy1
      @task = current_user.user_tasks.find(params[:id])
      @task.destroy
      redirect_to user_tasks_path, danger: "#{@task.name.capitalize} Todo Deleted" 
  end

  def manage
    @tasks = current_user.user_tasks.order(:id )
  end

  def show
  	@task = current_user.user_tasks.find(params[:id])
    @todos = @task.todos
    @total_count = @task.todos.count
    @completed = @task.todos.where(completed: true).count
    if @task.todos.exists? == true
      
      @width = @completed.to_f/@total_count * 100
        if @width==100
          
        end 
    else
      @width = 0
    end

  end

  private 

  def user_task_params
  	params.require(:user_task).permit(:name, :description, :user_id, todos_attributes: [:id, :name, :completed, :_destroy])
  end


end

app/helpers/user_tasks_helper.rb
module UserTasksHelper
end

app/views/user_tasks/_todo_fields.html.erb
<div class="nested-fields">
	<div class="row field">
		<div class="col-12 col-lg-6 col-md-8 animation">
			<% if action_name == "show" %>
					
				    <i class="far fa-stream" style="color: #E74292"></i> <%= f.text_field :name , onblur: "magic()" , class: "effect-3" , placeholder: "Please enter you Task" %>
				    <span class="focus-border"></span>
					
			    </div>
			    <div class="col-8 col-lg-6 col-md-4 animation float-right">
				    
				    <%= f.label :completed , class: "mr-1 comp" %>
				    
				    <div class="pretty p-icon p-smooth" id="pretty-scale-test">
				        <%= f.check_box :completed , id: "completed" , onclick: "magic()", class: "mr-2" %>
				        <div class="state p-success">
				            <i class="icon fa fa-check"></i>
				            <label></label>
				        </div>
				    </div>
			    	<i class="fas fa-trash" style="color:red"></i><%= link_to_remove_association "Delete", f, class: "text-danger", onclick: "fundel()" %>
				</div>
	    	<% else %>

	    		<i class="far fa-stream"></i> <%= f.text_field :name  , class: "effect-3" , placeholder: "Please enter you Task", style: "color: blue" %>
				    <span class="focus-border"></span>
					
			    </div>
			    <div class="col-8 col-lg-6 col-md-4 animation float-right">
				    <%= f.label :completed %>
				    <div class="pretty p-icon p-smooth" id="pretty-scale-test">
				        <%= f.check_box :completed , id: "completed", class: "mr-2" %>
				        <div class="state p-success">
				            <i class="icon fa fa-check"></i>
				            <label></label>
				        </div>
				    </div>
			    	<i class="fas fa-trash" style="color:red"></i><%= link_to_remove_association "Delete", f, class: "text-danger" %>
			    </div>
	    	<% end %>
	</div>
</div>	


<style>
	input:focus{outline: none; color: #0A79DF}
	input {
		text-transform: capitalize;
		color: #FF3031;
	}

	.animation{float: left; width: 27.33%; margin-bottom: 10px; position: relative;} /* necessary to give position: relative to parent. */
 
	.effect-3{border: 0; padding: 7px 0; border-bottom: 1px solid #ccc;}


	.effect-3 ~ .focus-border{position: absolute; bottom: 0; left: 0; width: 100%; height: 2px; z-index: 99;}

	.effect-3 ~ .focus-border:before, 
	.effect-3 ~ .focus-border:after{content: ""; position: absolute; bottom: 0; left: 0; width: 0; height: 100%; background-color: #3399FF; transition: 0.4s;}

		/*For Phone*/
		@media (max-width: 599px) { 

			.effect-3 {
				width: 100%
			}
        } 
          
        /*For Tablet*/    
       	@media (min-width:600px) {
       		.effect-3 {
				width: 90%
			}	
       	}
           
        @media (min-width: 801){ 
			.effect-3 {
				width: 90%
			}

        } 
 		
 		/*For Pc*/
        @media (min-width: 1281px) { 

            .effect-3 ~ .focus-border:before, 
			.effect-3 ~ .focus-border:after{content: ""; position: absolute; bottom: 0; left: 0; width: 0; height: 100%; background-color: #3399FF; transition: 0.4s;}
			.effect-3 {
				width: 90%
			}
        } 

	
	.effect-3 ~ .focus-border:after{left: auto; right: 0;}
	.effect-3:focus ~ .focus-border:before, 
	.effect-3:focus ~ .focus-border:after{width: 50%; transition: 0.4s;}

	

	#pretty-scale-test {
		font-size: 19px
	}

	.pretty {
		margin-right: 0;
	}

</style>

app/views/user_tasks/edit.html.erb
<div class="container">

  <h3 class="mb-3 mt-2">Edit - <%= @task.name.capitalize %></h3>

	<%= form_for @task do |form| %>
    <% if @task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@task.errors.count, "error") %> prohibited this Task from being saved:</h2>

        <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="field col-12 col-lg-9">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>
      <div class="col-lg-3"></div>
    </div>

    <div class="row">
      <div class="field col-12 col-lg-9">
        <%= form.label :description %>
        <%= form.text_field :description, class: 'form-control' %>
      </div>
      <div class="col-lg-3"></div>
    </div>

    <%= form.hidden_field :user_id, value: current_user.id %>

    <h4 class="mt-2 mb-2">Add Task/s</h4>
    <%= form.fields_for :todos do |todo| %>
      <%= render 'todo_fields', f: todo %>
    <% end %>
    <div class="links">
    <%= link_to_add_association "Add Task", form, :todos , class: "btn btn-warning" %>
    </div>

    <div class="actions text-center">
      <%= form.submit "Update", class: "btn btn-success mt-3", id: "update1" %> 
      <button type="button" class="btn btn-danger mt-3" data-toggle="modal" data-target="#exampleModal">Delete this Todo
      </button>
    </div>
  <% end %>

    <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header bg-danger">
                <h5 class="modal-title text-white" id="exampleModalLongTitle">Delete</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                Are you sure to delete <span><b><%= @task.name.capitalize %></b></span> ?
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <%= link_to "Delete" , destroy1_path(@task), method: :delete, class: "btn btn-danger" %>
              </div>
            </div>
          </div>
        </div>

</div>

<style>
  .neat {
          min-height: calc(100vh - 110px);
         }
</style>

app/views/user_tasks/index.html.erb
<%= render 'shared/notice' %>
<center>
	<%= link_to '<i class="fas fa-plus"></i> <b>Create New Todo</b>'.html_safe, new_user_task_path, :class => "btn btn-primary mb-3 color1 mt-2" %>
</center>

<div class="container">
	<div class="row"> 

		<div class="col-lg-6 col-12 col-sm-6 mb-4">
			<div class="card" >
			  <div class="card-header">
			    <h3><i class="fas fa-tasks"></i> <b> All Todo's</b></h3>
			  </div>
			</div>
			<% @tasks.each do |task| %>
				<div class="tasks mt-2 md-3">

					<i class="fal fa-edit"></i> <%= link_to task.name.capitalize, user_task_path(task) %>
					
					<% if task.todos.where(completed: true).count == task.todos.count && task.todos.count != 0 %>
						<span class="badge badge-success float-right">Completed</span>
					<% elsif task.todos.count != 0 && task.todos.where(completed: true).count > 0 %>
					    <span class="badge badge-warning float-right">On progress</span>
					<% else %>
						<span class="badge badge-secondary float-right">Not started</span>
					<% end %>
				</div>
			<% end %>
		</div>

		<div class="col-lg-6 col-12 col-sm-6">
			<canvas id="myChart" width="300" height="180"></canvas>
			<div class="text-center">
				<!-- Total no of Todos - <%= current_user.user_tasks.count %><br> -->
				No of Todo's Completed - <b><%= current_user.user_tasks.where(completed: true).count %></b> <br>
				No of Todo's in Pending - <b><%= current_user.user_tasks.count - current_user.user_tasks.where(completed: true).count %></b> <br>
			</div>
			<div class="chill mt-4">
				<% if @quote.present? %>
			 <blockquote class="blockquote blockquote-custom bg-white pt-5 pb-4 pl-5 pr-3 shadow rounded"  >
                    <div class="blockquote-custom-icon bg-info shadow-sm"><i class="fa fa-quote-left text-white"></i></div>
                    <div class="blockquote-header"><h4 style="margin-left: -10px">MOTIVATE YOUR SELF</h4></div>
                    <p class="mb-0 mt-2  ml-1"><%= @quote.quotes.capitalize %></p>
                    <footer class="blockquote-footer mt-2 mb-1 ml-2">
                        <cite title="Source Title"><%= @quote.author %></cite> <span class="float-right mr-3">
                        	<% if current_user.admin %>
                        	<%= link_to "All Quotes", admin_quote_path , class: "btn btn-sm btn-success" %>
                        	<% else %>
                        	<%= link_to "All Quotes", user_quote_path , class: "btn btn-sm btn-success" %>
                        		<% end %>
                        	</span>
                    </footer>
                </blockquote>
                <% end %>
                </div>
		</div>

	</div>
</div>
  

<style >
	.tasks {
		background-color: #f1f1f1;
		border-radius: 8px;
		padding: 8px 20px 8px 40px;
		box-shadow: 5px 10px 30px #888888;
	}

	.badge {
		font-size: 13.4px
	}

	.color1 {
		background-color: #BB2CD9;
		border-color: #BB2CD9 
	}
	.btn-primary:hover, .btn-primary:focus, .btn-primary:active, .btn-primary.active, .open>.dropdown-toggle.btn-primary {
	    background-color: #BB2CD9;
	    border-color: #BB2CD9; /*set the color you want here*/
	}

	.blockquote-custom {
	  position: relative;
	  font-size: 1.1rem;
	}

	.blockquote-custom-icon {
	  width: 50px;
	  height: 50px;
	  border-radius: 50%;
	  display: flex;
	  align-items: center;
	  justify-content: center;
	  position: absolute;
	  top: -25px;
	  left: 50px;
	}


	/*For Phone*/
		@media (max-width: 599px) { 
			
		}
          
        /*For Tablet*/    
       	@media (min-width:600px) {
       		
        }

        @media (min-width: 801){ 
			

        } 
 		
 		/*For Pc*/
        @media (min-width: 1281px) { 
        	.chill {
			  height: 50%;
			  width: 60%;
			  margin: auto;
			} 
            
        }
</style>  

<script >
	var completed = <%= current_user.user_tasks.where(completed: true).count %>;
	var total = <%= current_user.user_tasks.count %>;
	var notcompleted = total - completed;
	var ctx = document.getElementById('myChart');
	
	var myChart = new Chart(ctx, {
	    type: 'horizontalBar',
	    data: {
	        labels: [ 'Completed',  'Pending', 'Total'],
	        datasets: [{
	            label: "of Todo's",
	            data: [ completed, notcompleted, total],
	            backgroundColor: [
	                'rgba(127, 255, 0, 0.2)',
	                'rgba(255, 206, 86, 0.2)',
	                'rgba(0,191,255, 0.2)'
	            ],
	            borderColor: [
	                'rgba(127,255,0, 1)',
	                'rgba(255, 206, 86, 1)',
	                'rgba(0,191,255, 1)'
	            ],
	            borderWidth: 2
	        }]
	    },
	    options: {
	    	title: {
	            display: true,
	            text: 'Graphical Representation'
	        },
	        scales: {
	            xAxes: [{barThickness: 10, 
	                ticks: {
	                    beginAtZero: true
	                }
	            }]
	        }
	    }
	});
</script>
<style>
    .descriptive {
      font-size: 19px;
    }
    .neat {
            min-height: calc(100vh - 10px);
           }
  </style>

app/views/user_tasks/manage.html.erb
<%= render 'shared/notice' %>
<div class="scrollmenu overflowTest">
	<div class="horizontal-scrollable">
	<table class="table table-striped ">
	  <thead>
	    <tr>
	      <th scope="col"><center>Todo's(<%= current_user.user_tasks.count %>)</center></th>
	      <th scope="col"><center>Details</center></th>
	      <th scope="col">Created </th>
	      <th scope="col">Actions</th>
	    </tr>
	  </thead>
	  <tbody>
	  	<% @tasks.each do |task| %>
		    <tr>
		      <td><center><%= link_to task.name.capitalize, user_task_path(task)  %></center></td>
		      <td><center>
		      	<% if task.todos.exists? %>
		      	<% percent = task.todos.where(completed: true).count.to_f/task.todos.count  * 100 %> <%= percent.to_i %> % completed
		      	<% else %>
		      		No tasks
		      	<% end %>
		      </center></td>
		      <td><%= task.created_at.strftime("%B %e, %Y") %></td>
		      <td>
		      	
		      	<strong><%= link_to "Edit", edit_user_task_path(task) %></strong>

		      	<strong>
		      		<a class="text-danger" 
	         data-toggle="modal" data-target="#exampleModal<%= task.id %>">
	     		Delete</a>
	    		</strong>

					<!-- Modal -->
					<div class="modal fade" id="exampleModal<%= task.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
					  <div class="modal-dialog modal-dialog-centered" role="document">
					    <div class="modal-content">
					      <div class="modal-header bg-danger">
					        <h5 class="modal-title text-white" id="exampleModalLongTitle">Delete</h5>
					        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
					          <span aria-hidden="true">&times;</span>
					        </button>
					      </div>
					      <div class="modal-body">
					        Are you sure to delete <span class="text-danger"><strong><%= task.name.capitalize %></strong></span> Todo?
					      </div>
					      <div class="modal-footer">
					        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					        <%= link_to "Delete" , task, method: :delete, class: "btn btn-danger" %>
					      </div>
					    </div>
					  </div>
					</div>
				</td>
		    </tr>
	  	<% end %>
	  </tbody>
	</table>
</div>
</div>

<style >
	div.scrollmenu {
	  overflow: auto;
	  white-space: nowrap;
	}

	/*.overflowTest {
	  height: 600px;
	  overflow: scroll;
	}*/
    .descriptive {
      font-size: 19px;
    }
    .neat {
            min-height: calc(100vh - 143px);
           }
</style>

app/views/user_tasks/new.html.erb
<div class="container">

  <h1>Create To-do list </h1>
  <div class="row">
    <div class="col-12 col-lg-2"></div>
    <div class="col-12 col-lg-7">
    	<%= form_for @task do |form| %>

        <div class="field">
          <%= form.label :todo_name %>
          <%= form.text_field :name, class: 'form-control', required: "true" %>
        </div>

        <div class="field">
          <%= form.label :description %>
          <%= form.text_field :description, class: 'form-control', placeholder: "optional", required: "true" %>
        </div>

        <%= form.hidden_field :user_id, value: current_user.id %>

        <h5 class="mt-1">( you can add as many tasks you want )</h5><br>
        <% form.fields_for :todos do |todo| %>
          <%= render 'todo_fields', f: todo %>
        <% end %>
        <div class="links">
        <%= link_to_add_association "Add task", form, :todos, class: "btn btn-warning btn-sm", id: "lazy" %>
        </div>

        <div class="actions">
          <center><%= form.submit "Create ", class: "btn btn-success btn-lg mt-3" %></center>
        </div>
      <% end %>
    </div>
    <div class="col-12 col-lg-2"></div>
  </div>
  <div class="text-center text-danger mt-5"><b style="font-size: 15px"><%= @quote.quotes.capitalize %></b></div>
  

</div>
  <style>
    .neat {
            min-height: calc(100vh - 143px);
           }
  </style>
  <script >
    function hello() {
      var lazy = document.getElementById("lazy").click();
    }
    del = setTimeout(hello, 100)
  </script>

app/views/user_tasks/show.html.erb
<%= render 'shared/notice' %>
<div class="container">

	<div class="progress mt-3" style="height: 20px">
	  <div class="progress-bar bg-danger progress-bar-striped progress-bar-animated" role="progressbar" id="test" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width:<%= @width.to_i %>%"><%= @width.to_i %> %</div>
	</div>
	<center>
		<% if @completed == @total_count %>
			<% if @completed == 1 %>
				<span class="descriptive">All Tasks are completed</span> 
			<% else %>
			  <span class="descriptive">All <%= @total_count %> Tasks are Completed</span>
			<% end %>

		<% elsif  @completed == 0 %>
			<%= @completed %> out of <%= @total_count %> are completed, Remember Every-thing Start from zero.
		<% else %>
			<%= @completed %> out of <%= @total_count %> Task/s are completed
		<% end %>
	</center>

	<h2 class="ml-3">Todo - <%= @task.name.capitalize %> </h2>
	<div>
		Description - <%= @task.description.capitalize %>
	</div>
	
	<center>
		<div class="mb-4">
			<%= link_to "Edit", edit_user_task_path , class: "btn btn-primary mr-2 " %>
			<button class="btn btn-warning" onclick="task()">Add Task</button>
		</div>
	</center>

	
	<%= form_for @task do |form| %>

	    <%= form.hidden_field :user_id, value: current_user.id %>
	    <%= form.fields_for :todos do |todo| %>
	      <%= render 'todo_fields', f: todo %>
	    <% end %>

	    <div class="links" id="scrolll">
	    <%= link_to_add_association "Add Task", form, :todos , id: "task1" , style: "display: none" %>
	    </div>

	    <div class="actions">
	      <%= form.submit "Update", class: "btn btn-success mt-3", id: "update1" , :style => "display: none;" %>
	    </div>
	<% end %>

</div>
</div>


<script >
 
 var end = Date.now() + (2 * 400);
 var colors = ['#bb0000', '#FFF222', '#34eb4f', '#2B2B52'];
 var width = <%= @width %>
 
	if (width==100.0) {
		(function frame() {
		  confetti({
		    particleCount: 10,
		    angle: 60,
		    spread: 300,
		    origin: { x: 0 },
		    colors: colors
		  });
		  confetti({
		    particleCount: 10,
		    angle: 120,
		    spread: 300,
		    origin: { x: 1 },
		    colors: colors
		  });

		  if (Date.now() < end) {
		    requestAnimationFrame(frame);
		  }
		}());
	};

	function task(){
		document.getElementById("task1").click();
		document.getElementById("scrolll").scrollIntoView();
	};

	function magic() {
		document.getElementById('update1').click();
	}

	function fundel() {
		var del;
		del = setTimeout(magic, 100)
	}

</script>

<style>
	.descriptive {
		font-size: 19px;
	}
	.neat {
          min-height: calc(100vh - 143px);
         }
</style>